### ISSUE TITLE
Is there a way to change the proto file or make additions without them being overwritten?

### ISSUE THREAD

**Issue by JamesArthurHolland** [walterwanderley/sqlc-grpc#10]
I have the following schema:

```mysql
--pricing_schema.sql

CREATE TABLE pricing_schema (
    id UUID PRIMARY KEY,
    name varchar(255) NOT NULL,
    organization_id UUID NOT NULL,
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    updated_at timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE price_category (
    id UUID PRIMARY KEY,
    name varchar(255) NOT NULL,
    pricing_schema_id UUID NOT NULL,
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    updated_at timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE price (
    id UUID PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    price_category_id UUID NOT NULL,
    price_in_smallest_donimation int NOT NULL,
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    updated_at timestamp NOT NULL DEFAULT current_timestamp
);
```

I want to be able to use transactions to save a full pricing schema at once, including the nested parts.

schema
  -> category1
     ----> item1
  -> category2
     ----> item1
     ----> item2

I have the individual methods / queries for saving, but how do I create the addition to the proto file / grpc schema without having to write a sql query for the insert?

**Comment by walterwanderley** [comment]
At this moment it's impossible. Just proto comments and options aren't overwrited. I'll try to implement this feature on the next release.

**Comment by JamesArthurHolland** [comment]
Do you have an idea of how this would be implemented?

I have some spare time right now, I could potentially contribute a PR if you could discuss implementation details?

**Comment by walterwanderley** [comment]
> Do you have an idea of how this would be implemented?
> 
> I have some spare time right now, I could potentially contribute a PR if you could discuss implementation details?

Try the new version v0.19.3.

**Comment by JamesArthurHolland** [comment]
The proto file still gets overwritten each time `go generate` runs

```
$ sqlc-grpc -v
v0.19.3
```

**Comment by walterwanderley** [comment]
Could you provide an example of a modified proto file?
