### ISSUE TITLE
regenerating after sql file update overwrites swagger options

### ISSUE THREAD

**Issue by TColl** [walterwanderley/sqlc-grpc#3]
## Steps to reproduce

1. write sql query/schema
2. run `sqlc generate`
3. run `sqlc-grpc -m "<path>"`
4. edit swagger API details in `proto/model/v1/model.proto` to replace the placeholder entries
5. modify a sql file
6. per the [instructions](https://github.com/walterwanderley/sqlc-grpc/blob/main/README.md?plain=1#L97), run `sqlc generate && go generate`

The custom swagger details in `proto/model/v1/model.proto` are now reverted to the placeholder entries, rather than preserving our own details.

**Comment by walterwanderley** [comment]
Hi @TColl, thanks for the contribution!

Can you update to latest version (v0.10.0)?

**Comment by TColl** [comment]
confirmed this is now sorted with v0.10.0 - thanks!
