### ISSUE TITLE
Underscore in package name causes error

### ISSUE THREAD

**Issue by JamesArthurHolland** [walterwanderley/sqlc-grpc#7]
sqlc.yaml
```
version: "1"
packages:
  - path: "internal/package_name"
```

package_name instead of packagename causes an unfound error for unimplemented server.

Dunno if that's an sqlc issue or from here.

**Comment by walterwanderley** [comment]
@JamesArthurHolland thank you for your bug report.

Version v0.16.4 fixed it!
